### ISSUE TITLE
MongoDB docker-compose restart policy change

### ISSUE THREAD

**Issue by Zrad** [OctoFarm/OctoFarm-Documentation#20]
Currently, the MongoDB service has a typo in the restart policy. It reads "restart: unless_stopped" when it should be "restart: unless-stopped"

**Comment by NotExpectedYet** [comment]
Hey cheers for pointing that out, will sort it.

**Comment by NotExpectedYet** [comment]
Those are fixed. I also update the other restart: always commands as that should have also been unless-stopped.
